# Generated by Django 3.1.2 on 2020-10-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
    ]
