version: '3.5' # We use version 3.5 syntax

services: # Here we define our service(s)

    angular-service: # The name of the service
        container_name: angularcontainer  # Container name
        build: ./angular-hkb # Location of our Dockerfile
        volumes: # Volume binding
          - './angular-hkb:/usr/src/app'
        ports:
          - '4200:4200' # Port mapping
        command: >
          bash -c "npm install && ng serve  --host 0.0.0.0 --port 4200"

    nginx-service:
        container_name: nginxcontainer
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 80:80

    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    django-service:
        container_name: djangocontainer
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django-hkb:/usr/src/app
        ports:
            - 8000:8000



